//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuisine
    {
        public Cuisine()
        {
            this.Dish = new HashSet<Dish>();
            this.Menu = new HashSet<Menu>();
        }
    
        public string cuisine_name { get; set; }
        public string cuisine_imageURL { get; set; }
        public string cuisine_description { get; set; }
    
        public virtual ICollection<Dish> Dish { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
