//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiningTable
    {
        public DiningTable()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int dintable_No { get; set; }
        public int dintable_numberOfChairs { get; set; }
        public bool dintable_status { get; set; }
        public int dintable_sectionID { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
