//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.Item = new HashSet<Item>();
            this.Recipe = new HashSet<Recipe>();
        }
    
        public int dish_id { get; set; }
        public string dish_name { get; set; }
        public string dish_description { get; set; }
        public int dish_price { get; set; }
        public string dish_imageURL { get; set; }
        public string class_name { get; set; }
        public string cuisine_name { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Cuisine Cuisine { get; set; }
        public virtual ICollection<Item> Item { get; set; }
        public virtual ICollection<Recipe> Recipe { get; set; }
    }
}
