//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int news_id { get; set; }
        public System.DateTime news_datetime { get; set; }
        public string news_imageURL { get; set; }
        public string news_text { get; set; }
        public string news_restName { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
