//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.DiningTable = new HashSet<DiningTable>();
        }
    
        public int order_id { get; set; }
        public System.DateTime order_datetime { get; set; }
        public string order_author { get; set; }
        public string order_description { get; set; }
        public string order_phone { get; set; }
        public System.DateTime order_timeReservation { get; set; }
    
        public virtual ICollection<DiningTable> DiningTable { get; set; }
    }
}
