//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.Menu = new HashSet<Menu>();
            this.News = new HashSet<News>();
            this.Reviews = new HashSet<Reviews>();
            this.Section = new HashSet<Section>();
        }
    
        public string rest_name { get; set; }
        public string rest_contact { get; set; }
        public string rest_address { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<Section> Section { get; set; }
    }
}
