//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int reviews_id { get; set; }
        public System.DateTime reviews_datetime { get; set; }
        public string reviews_message { get; set; }
        public string reviews_restName { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
    }
}
