//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.DiningTable = new HashSet<DiningTable>();
        }
    
        public int section_id { get; set; }
        public string section_type { get; set; }
        public string section_restName { get; set; }
    
        public virtual ICollection<DiningTable> DiningTable { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
